---
# Tasks for sysbench stuff

- name: install sysbench
  yum: name=sysbench state=installed

- name: symlink ca.pem
  file:
    src: "/etc/ssl/mysql/ca.pem"
    dest: "/etc/ssl/mysql/cacert.pem"
    state: link
